apiVersion: apps/v1
kind: Deployment
metadata:
  name: boot-to-k8s-deployment
spec:
  template:
    spec:
      containers:
        - name: boot-to-k8s
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 4
            periodSeconds: 3
          readinessProbe:
            initialDelaySeconds: 4
            periodSeconds: 10
            httpGet:
              path: /
              port: 8080
