apiVersion: apps/v1
kind: Deployment
metadata:
  name: boot-to-k8s
spec:
  template:
    spec:
      containers:
        - name: boot-to-k8s
          env:
          - name: environment
            value: production
