apiVersion: v1
kind: Service
metadata:
  name: boot-to-k8s-service
  labels:
    app: boot-to-k8s
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: boot-to-k8s
  type: ClusterIP