apiVersion: v1
kind: Secret
metadata:
  name: github-credentials
  namespace: boot-to-k8s
  annotations:
    build.pivotal.io/git: https://github.com/
type: kubernetes.io/basic-auth
stringData:
  username: @github-user@
  password: @github-password@
