apiVersion: build.pivotal.io/v1alpha1
kind: Image
metadata:
  name: boot-to-k8s
  namespace: boot-to-k8s
spec:
  build:
    resources: {}
  builder:
    kind: CustomClusterBuilder
    name: default
  cacheSize: 2G
  failedBuildHistoryLimit: 10
  imageTaggingStrategy: BuildNumber
  serviceAccount: boot-to-k8s-sa
  source:
    git:
      revision: master
      url: https://github.com/@github-user@/boot-to-k8s.git
  successBuildHistoryLimit: 10
  tag: index.docker.io/@dockerhub-user@/boot-to-k8s
